### ISSUE TITLE
As a user I want to create a new Mapping

### ISSUE THREAD

**Issue by fteem** [OpenFn/OpenFn-Site#153]
- [x] /mapping/new creates and redirects to /mapping/:id/edit
- [x] If I change the label, save button lights up
- [x] If I click save, it saves and gives me feedback (growl style?)
- [x] add feature flags to the routes in rails for legacy routes

**Comment by stuartc** [comment]
### Getting to Develop

- [ ] Test existing app without `NEW_MAPPING_PAGE`

Things to look out for, errors in console... Check for xhr for pretty much all changes.

**Comment by stuartc** [comment]
- [ ]  add feature flags to the routes in rails for legacy routes

**Comment by taylordowns2000** [comment]
@fteem i imagine this is related to the bugs i've found with #155... nothing is saving :-)
