### ISSUE TITLE
As a user I want to configure a Product

### ISSUE THREAD

**Issue by fteem** [OpenFn/OpenFn-Site#154]
- [x] Opening a mapping, fetches a list of available Source & Destination profiles
- [x] I click "Add new xyz", I get a modal for a new "ConnectionProfile" for that product.

- [x] STI and validation for both ODK and Salesforce.
- [ ] When it's valid, fetch and store ObjectDescriptions

- [x] ConnectionProfile belongs_to :credential
- [x] Credential is created through ConnectionProfile (with nested attrs)

### Forms
- [x] Form for ODK
- [x] Form for Salesforce

- [x] use adaptor key from ConnectionProfiles to open the correct form
  - [x] ODK adapter
  - [x] Salesforce Adaptor

### Credential Subclasses
- [x] ODK < Credential
- [x] Salesforce < Credential

### ODK validations
- [x] username
- [x] password
- [x] url

### Salesforce validations
- [x] check the name of these fields in salesforce settings
- [x] host
- [x] app_secret
- [x] app_key
- [x] security_token

### Check credentials against server
- [x] only if changed/new
- [x] need new `verified` datetime column
- [x] when we check we clear `verified`
- [x] credential only valid if verified != nil
- [ ] #recheck (without change) (if it makes dev easier)

**Comment by stuartc** [comment]
### Endpoints

```
GET /api/v1/connection_profiles/?type=source
GET /api/v1/connection_profiles/?type=destination
```

```json
[
  {
    "id": 1
    "name": "aaa",
    "product": "odk"
  },
  {
    "id": null,
    "product": "odk"
  }
]

```

**Comment by stuartc** [comment]
- [ ] scope for `Product.where(integrated: true)`
- [ ] `AvailableConnectionProfiles.for` factory

```ruby
# integrated_products is just an array, we need to preselect either source or destination ones.
AvailableConnectionProfiles.for(user.id,integrated_products)
```

**Comment by fteem** [comment]
Only for Ile's eyes!!!!!!!!!! xD

- ConnectionProfilesController 
	- you can make a scope on Product.where(integrated: true) (means we have a driver for this Product)
	- returns all the ConnectionProfile that the user has created + all the integrated Products
	- all ConnectionProfile should have a product_id (association between Product and ConnectionProfile)
	- ConnectionProfile belongs_to Product, Product has_many ConnectionProfiles

- ConnectionProfile 
	- belongs_to :user

- User
	- has_many :connection_profiles

**Comment by stuartc** [comment]
- [ ] ConnectionProfile belongs_to :credential
- [ ] Credential is created through ConnectionProfile (with nested attrs)

### Credential Subclasses
- [ ] ODK < Credential
- [ ] Salesforce < Credential

### ODK validations
- [ ] username
- [ ] password
- [ ] url

### Salesforce validations
- [ ] check the name of these fields in salesforce settings
- [ ] host
- [ ] app_secret
- [ ] app_key
- [ ] security_token

### Check credentials against server
- [ ] only if changed/new
- [ ] need new `verified` datetime column
- [ ] when we check we clear `verified`
- [ ] crediential only valid if verified != nil
- [ ] #recheck (without change) (if it makes dev easier)


### Forms
- [ ] use adaptor key from ConnectionProfiles to open the correct form

**Comment by stuartc** [comment]
Credentials model

belongs_to :connection_profile

type column

all subclasses are < Credential

add hstore attrs for each one.
validations...

add verified datetime
