### ISSUE TITLE
As a user I want to select a Product

### ISSUE THREAD

**Issue by fteem** [OpenFn/OpenFn-Site#155]
- [x] I see a list of ConnectionProfiles
  - [x] both Source and Destination
- [x] I click it, mapping gets autosaved.

**Comment by taylordowns2000** [comment]
@fteem , when i add a new destination credential it doesn't appear in the list. i need to load a new page to make it appear.

**Comment by taylordowns2000** [comment]
@fteem when i refresh the page, i get a "doesn't exist" error: https://staging-openfn.herokuapp.com/mappings/6/edit - does not exist.

**Comment by fteem** [comment]
@taylordowns2000 can you please retest this. Also, the "doesn't exist" error will remain until we remove the old Mappings controller and swap them with Angular views

**Comment by fteem** [comment]
@taylordowns2000 also, this is currently working without autosave. Would you prefer I do it with autosave or it's okay if the user clicks on the Save button after choosing a product?

**Comment by taylordowns2000** [comment]
With autosave, please. (Has autosave not been built for any of the page
yet? or is it not working JUST for this feature?)

**Comment by fteem** [comment]
@taylordowns2000 it is not been built for any of the page. There's a save button that is enabled when the form is valid. It's not a big feat, I'll add it now.
