### ISSUE TITLE
Allow logged in users to rate and review technologies

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#181]
- [x] Review initial work on this branch: https://github.com/OpenFn/OpenFn-Site/commit/0a4b29cbcdb16794d08cdfa03eec0ca9a7ada3a4
- [x] Create review table, linked to product (product, rating, review, user, date)
- [x] Create review modal that pops up when review button is clicked and allows user to submit a new review.
- [x] Create "review_vote" table which belongs to "review" and carries a +1 or -1 value.
- [x] Allow users to vote on reviews as either "+1, this review is useful" or "-1, this review is not useful."
- [x] display list of reviews, with review scores (votes) on the "reviews" tab in the product listing.
- [x] Calculate product rating = (sum of (review rating * (IF(review_vote_score>=0, max(review_vote_score, 1), 0) / sum of (IF(review_vote_score>=0, max(review_vote_score, 1))
- [x] Display product rating
- [x] Ensure that each use can only vote once up or once down for a single product. If they have an upvote, they can replace it with a downvote. If they have a downvote, they can replace it with an upvote. They cannot vote more than once for each product.
- [x] Sort reviews by review score (higher at the top)
- [x] only allow a single review per product by each user.

**Comment by kartik-biz4** [comment]
Taylor, Do we want the upvote and downvote labels to get disabled if user has already voted or a check at backend side should be sufficient ?

**Comment by taylordowns2000** [comment]
Disabled, please. Thanks, Kartik.

Taylor
