### ISSUE TITLE
Sort out notifications.

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#212]

**Comment by taylordowns2000** [comment]
@nicc , hey dude, what did you mean by this?

**Comment by nicc** [comment]
Hey @taylordowns2000 !
I don't remember this. Where is it from? Did we have a backlog story for it?
Notifications could mean incoming SOAP messages from Salesforce, or user notifications in-browser. Could you give me context about the original statement?

**Comment by taylordowns2000** [comment]
Ah! Found it in the notes on the old trello card. My bad. (Not sure how I
missed that.)

It's billing notifications (done, stripe), failures (got a separate card
for this), and expired credentials (will add a separate card.)

Thanks, Nic.

TD
