### ISSUE TITLE
rake db:migrate fails

### ISSUE THREAD

**Issue by debonair** [OpenFn/OpenFn-Site#230]
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `role' for #<User:0x000000093e4960>/home/duma/Projects/OpenFn-Site/app/models/user.rb:138:in `set_default_role'
/home/duma/Projects/OpenFn-Site/db/migrate/20140709013638_create_default_user_and_set_mapping_owner.rb:3:in `change'
NoMethodError: undefined method `role' for #<User:0x000000093e4960>
/home/duma/Projects/OpenFn-Site/app/models/user.rb:138:in `set_default_role'
/home/duma/Projects/OpenFn-Site/db/migrate/20140709013638_create_default_user_and_set_mapping_owner.rb:3:in `change'
Tasks: TOP => db:migrate

**Comment by taylordowns2000** [comment]
Thank you @debonair , fixing this shortly. for now, @rorymckinley has been able to setup clean using the following:

RAILS_ENV=test bundle exec rake db:schema:load
You can change the RAILS_ENV value to development for the dev DB

**Comment by AlexBailey20** [comment]
== 20140709013638 CreateDefaultUserAndSetMappingOwner: migrating ==============
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `role' for #<User:0x007fcf6e256ee0>/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/attribute_methods.rb:435:in `method_missing'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/attribute_methods.rb:213:in `method_missing'
/home/alex/OpenFn-Site/app/models/user.rb:140:in `set_default_role'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/validations.rb:317:in `valid?'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:70:in `valid?'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:77:in `perform_validations'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:57:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `block in save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:41:in `create!'
/home/alex/OpenFn-Site/db/migrate/20140709013638_create_default_user_and_set_mapping_owner.rb:3:in `change'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:602:in `exec_migration'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:585:in `block in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:584:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:759:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `role' for #<User:0x007fcf6e256ee0>
/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/attribute_methods.rb:435:in `method_missing'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/attribute_methods.rb:213:in `method_missing'
/home/alex/OpenFn-Site/app/models/user.rb:140:in `set_default_role'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activemodel-4.1.9/lib/active_model/validations.rb:317:in `valid?'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:70:in `valid?'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:77:in `perform_validations'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:57:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `block in save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `save!'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/validations.rb:41:in `create!'
/home/alex/OpenFn-Site/db/migrate/20140709013638_create_default_user_and_set_mapping_owner.rb:3:in `change'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:602:in `exec_migration'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:585:in `block in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:584:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:759:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
/home/alex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.9/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate

**Comment by taylordowns2000** [comment]
hey @debonair , we've fixed this on develop and will be releasing to master later this week. thanks again for your help!
