### ISSUE TITLE
Clean marketplace index page

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#341]
- [x] create collapsible horizontal filters pane.
- [ ] make search bar look and behave as a filters bar (see tag filter edit pane on individual products for example) because it's NOT actually a search bar.
- [x] increase white-space to present cleaner, simpler layout.

![openfn-market-filter-run1 - oho comments](https://cloud.githubusercontent.com/assets/8732845/9190462/d56f1250-3ff5-11e5-995c-f863c347a2a6.jpg)

**Comment by suninthesky** [comment]
@taylordowns2000 I've made two of the three [changes] (https://github.com/OpenFn/OpenFn-Site/tree/f341_market), but the search bar implementation is holding me up. I'm not going to have any time this weekend to complete it and is seems a shame not to merge completed changes (could split out the search implementation into it's own issue) to start getting user feedback. Let me know how you want to proceed.

**Comment by taylordowns2000** [comment]
@suninthesky , as far as i can tell, the search bar is working as i had planned! I'm going to make a small change to the bottom buttons and would love to talk to you about the spacing... can we fit 3 in a row on high-res displays? (it looks like TOO much whitespace on my machine.)

Bottom line is that this is beautiful! Thank you! It's now up at https://staging-openfn.herokuapp.com/marketplace. I'll be asking for feedback over the next few days. Would love if you could ask a couple buddies what they think. Unless you have a more scientific way I'll just open up openfn.org/marketplace next to staging-openfn.herokuapp.com/marketplace and ask which folks like better.

**Comment by suninthesky** [comment]
Thanks @taylordowns2000. I'll look into a three column layout for higher resolution displays. There are a few cross browser issues I've found which I'll fix as well. And I'll let you know what feedback throws up.

**Comment by suninthesky** [comment]
@taylordowns2000 I've made the changes, might be worth testing across multiple devices when gathering feedback. Initial testing I've done throws up a few styling issues at xl and mobile resolutions.

**Comment by taylordowns2000** [comment]
I've run inspector on Chrome and done really basic device testing for
various sizes and it looks good. So far, the only issue I'm having is that
search text doesn't appear in the input when I type on Firefox. Have you
seen this issue?

Somehow the typeahead sees what value is being entered, but it's not
readable in the white bar for the user.

Taylor

**Comment by suninthesky** [comment]
@taylordowns2000 the Firefox issue was interesting, thought it looks like the `content-box` fix did the trick. I've made a couple of tweaks to ensure a consistent width for the search box, but other than that I think we're good to go.
