### ISSUE TITLE
Limit Legacy Mappings by Submissions per Month

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#85]
If we determine that we cannot move to the modular app before the end of February, we must limit Legacy Mappings by the number of Legacy Submissions each month. This is related to issue #86 .

**Comment by taylordowns2000** [comment]
Limit the number of submissions per month for each User based on their Plan.

The submissions for a given billing period must be counted and that counter must be reset at the end of the Stripe billing period.

This count, and the date by which the counter will reset must be displayed to the user on the Mappings Index page.

Plan has a "job_limit" field which is sometimes called the "submission limit" in the front end.

**Comment by taylordowns2000** [comment]
"Stripe charges customers on the same day each billing cycle that the subscription was originally created. So, a customer subscribed to a monthly plan on the 20th will be billed on the 20th of each month. Can this be changed so that a customer who subscribed to a monthly plan on the 20th will really be billed on the 1st of each month?"

**Comment by stuartc** [comment]
**Getting the count of Legacy Submissions for billing period**

```ruby
user = User.find(4)
OdkSfLegacy::Submission.joins(import: {mapping: :user}).
  where(users: {id: user.id}).
  where(
    "submissions.created_at BETWEEN ? AND ?", 
    user.stripe_curent_period_end - 1.month, stripe_curent_period_end
  ).count
# => 45
```
*Watch out for Free users* they don't have a `stripe_curent_period_end` so we will need to use something else like:

```ruby
Date.current.beginning_of_month, Date.current.end_of_month
```
